#  devtools
debug: true
spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false

#jdp
  datasource:
    url: jdbc:mysql://212.64.83.246:3306/2021bishe_yao?useUnicode=true&characterEncoding=utf8
    username: 2021bishe_yao
    password: 2017013010
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #控制台显示建表语句
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      #没有表新建，有表更新操作
      ddl-auto: update
server:
  port: 8181
